const sound=[
    {path:'Sounds/disgusting/1.flac',
     underground:'disgusting'
    },
    {path:'Sounds/disgusting/2.wav',
     underground:'disgusting'
    },
    {path:'Sounds/disgusting/3.mp3',
     underground:'disgusting'
    },
    {path:'Sounds/disgusting/4.mp3',
     underground:'disgusting'
    },
    {path:'Sounds/digusting/1.flac',
     underground:'disgusting'
    },
    {path:'Sounds/digusting/1.flac',
     underground:'disgusting'
    },
    {path:'Sounds/horrifying/1.wav',
     underground:'horrifying'
    },
    {path:'Sounds/horrifying/2.wav',
     underground:'horrifying'
    },
    {path:'Sounds/horrifying/3.wav',
     underground:'horrifying'
    },
    {path:'Sounds/ordinary/1.wav',
     underground:'ordinary'
    },
    {path:'Sounds/ordinary/2.flac',
     underground:'ordinary'
    },
    {path:'Sounds/ordinary/3.mp3',
     underground:'ordinary'
    },
    {path:'Sounds/ordinary/4.wav',
     underground:'ordinary'
    },
    {path:'Sounds/strange/1.wav',
     underground:'strange'
    },
    {path:'Sounds/strange/2.wav',
     underground:'strange'
    },
    {path:'Sounds/strange/3.mp3',
     underground:'strange'
    },
    {path:'Sounds/wet/1.wav',
     underground:'wet'
    },
    {path:'Sounds/strange/2.mp3',
     underground:'wet'
    }
]